# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Shuxin Lin
tagline:             '|| 林舒心,,Ծ‸Ծ,,'
description:         'Interested in algorithm, machine learning, deep learning, data science, etc.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

github_repo: https://github.com/ShuxinLin